<!-- 
RSS generated by JIRA (6.3.4#6332-sha1:51bc225ef474afe3128b2f66878477f322397b16) at Sun May 17 03:24:05 UTC 2015

It is possible to restrict the fields that are returned in this document by specifying the 'field' parameter in your request.
For example, to request only the issue key and summary add field=key&field=summary to the URL of your request.
For example:
https://issues.apache.org/jira/si/jira.issueviews:issue-xml/DERBY-5574/DERBY-5574.xml?field=key&amp;field=summary
-->
<rss version="0.92" >
<channel>
    <title>ASF JIRA</title>
    <link>https://issues.apache.org/jira</link>
    <description>This file is an XML representation of an issue</description>
    <language>en-uk</language>    <build-info>
        <version>6.3.4</version>
        <build-number>6332</build-number>
        <build-date>15-08-2014</build-date>
    </build-info>

<item>
            <title>[DERBY-5574] encryption test in encryption nightly suite test fails with ERROR XBM0S: Unable to rename file error</title>
                <link>https://issues.apache.org/jira/browse/DERBY-5574</link>
                <project id="10594" key="DERBY">Derby</project>
                    <description>&lt;p&gt;encryption tests in nightly are intermittently failing.  The suite runs same set of tests with a number of different&lt;br/&gt;
encryption algorithms.  Different ones of these runs sometimes fail.  &lt;/p&gt;

&lt;p&gt;What has changed on this nightly platform is that we are now running each jvm set of tests concurrently to&lt;br/&gt;
get better throughput.  This has changed load on machine and timing of operations.  Each JVM puts results&lt;br/&gt;
into a different part of file system.  &lt;/p&gt;

&lt;p&gt;At least after the fact the file being renamed still exists and the destination file does not exist.&lt;/p&gt;

&lt;p&gt;nightly test failure, jdk16, current 10.7 branch, windows.&lt;/p&gt;

&lt;p&gt;&lt;a href=&quot;http://people.apache.org/~myrnavl/derby_test_results/v10_7/windows/testlog/ibm16/1231439-derbyall_diff.txt&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://people.apache.org/~myrnavl/derby_test_results/v10_7/windows/testlog/ibm16/1231439-derbyall_diff.txt&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Failure Details:&lt;/p&gt;
&lt;ul&gt;
	&lt;li&gt;
	&lt;ul&gt;
		&lt;li&gt;
		&lt;ul&gt;
			&lt;li&gt;
			&lt;ul&gt;
				&lt;li&gt;
				&lt;ul&gt;
					&lt;li&gt;
					&lt;ul&gt;
						&lt;li&gt;
						&lt;ul&gt;
							&lt;li&gt;
							&lt;ul&gt;
								&lt;li&gt;
								&lt;ul&gt;
									&lt;li&gt;Diff file derbyall/derbynetclientmats/DerbyNetClient/encodingTests/TestEnc.diff&lt;/li&gt;
								&lt;/ul&gt;
								&lt;/li&gt;
							&lt;/ul&gt;
							&lt;/li&gt;
						&lt;/ul&gt;
						&lt;/li&gt;
					&lt;/ul&gt;
					&lt;/li&gt;
				&lt;/ul&gt;
				&lt;/li&gt;
			&lt;/ul&gt;
			&lt;/li&gt;
			&lt;li&gt;Start: TestEnc jdk1.6.0 DerbyNetClient derbynetclientmats:encodingTests 2012-01-14 01:42:10 ***&lt;br/&gt;
derbyTesting.encoding can only be used with jdk15, skipping test&lt;/li&gt;
			&lt;li&gt;End:   TestEnc jdk1.6.0 DerbyNetClient derbynetclientmats:encodingTests 2012-01-14 01:42:10 ***
			&lt;ul&gt;
				&lt;li&gt;
				&lt;ul&gt;
					&lt;li&gt;
					&lt;ul&gt;
						&lt;li&gt;
						&lt;ul&gt;
							&lt;li&gt;
							&lt;ul&gt;
								&lt;li&gt;
								&lt;ul&gt;
									&lt;li&gt;Diff file derbyall/encryptionAll/encryptionAES/encryptDatabase.diff&lt;/li&gt;
								&lt;/ul&gt;
								&lt;/li&gt;
							&lt;/ul&gt;
							&lt;/li&gt;
						&lt;/ul&gt;
						&lt;/li&gt;
					&lt;/ul&gt;
					&lt;/li&gt;
				&lt;/ul&gt;
				&lt;/li&gt;
			&lt;/ul&gt;
			&lt;/li&gt;
			&lt;li&gt;Start: encryptDatabase jdk1.6.0 encryptionAll:encryptionAES 2012-01-14 01:51:40 ***&lt;br/&gt;
74 del&lt;br/&gt;
&amp;lt; 0 rows inserted/updated/deleted&lt;br/&gt;
74a74,76&lt;br/&gt;
&amp;gt; ERROR 38000: The exception &apos;org.apache.derby.iapi.error.PassThroughException: encryptionAll:encryptionAES &apos;F:\jartest\JarResults.2012-01-13\ibm16_derbyall\derbyall\encryptionAll\encryptionAES\encryptDatabase\wombat\service.properties&apos; to &apos;F:\jartest\JarResults.2012-01-13\ibm16_derbyall\derbyall\encryptionAll\encryptionAES\encryptDatabase\wombat\service.propertiesold&apos;&apos; was thrown while evaluating an expression.&lt;br/&gt;
&amp;gt; ERROR XJ001: Java exception: &apos;ERROR XBM0S: Unable to rename file &apos;F:\jartest\JarResults.2012-01-13\ibm16_derbyall\derbyall\encryptionAll\encryptionAES\encryptDatabase\wombat\service.properties&apos; to &apos;F:\jartest\JarResults.2012-01-13\ibm16_derbyall\derbyall\encryptionAll\encryptionAES\encryptDatabase\wombat\service.propertiesold&apos;: org.apache.derby.iapi.error.PassThroughException&apos;.&lt;br/&gt;
&amp;gt; ERROR XBM0S: Unable to rename file &apos;F:\jartest\JarResults.2012-01-13\ibm16_derbyall\derbyall\encryptionAll\encryptionAES\encryptDatabase\wombat\service.properties&apos; to &apos;F:\jartest\JarResults.2012-01-13\ibm16_derbyall\derbyall\encryptionAll\encryptionAES\encryptDatabase\wombat\service.propertiesold&apos;&lt;br/&gt;
94,95d95&lt;br/&gt;
&amp;lt; ERROR XJ040: Failed to start database &apos;wombat&apos; with class loader XXXX,  see the next exception for details.&lt;br/&gt;
&amp;lt; ERROR XBM06: Startup failed. An encrypted database cannot be accessed without the correct boot password.  &lt;br/&gt;
97 del&lt;br/&gt;
&amp;lt; ij&amp;gt; values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY(&apos;bootPassword&apos;);&lt;br/&gt;
97a97&lt;br/&gt;
&amp;gt; ij(CONNECTION1)&amp;gt; values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY(&apos;bootPassword&apos;);&lt;br/&gt;
101 del&lt;br/&gt;
&amp;lt; ij&amp;gt; values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY(&apos;encryptedBootPassword&apos;);&lt;br/&gt;
101a101&lt;br/&gt;
&amp;gt; ij(CONNECTION1)&amp;gt; values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY(&apos;encryptedBootPassword&apos;);&lt;br/&gt;
105 del&lt;br/&gt;
&amp;lt; ij&amp;gt; &amp;#8211; change it again, make sure it trims white spaces&lt;br/&gt;
105a105&lt;br/&gt;
&amp;gt; ij(CONNECTION1)&amp;gt; &amp;#8211; change it again, make sure it trims white spaces&lt;br/&gt;
107 del&lt;br/&gt;
&amp;lt; 0 rows inserted/updated/deleted&lt;br/&gt;
108 del&lt;br/&gt;
&amp;lt; ij&amp;gt; call SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY(&apos;bootPassword&apos;, &apos;bbderbypwdx, derbypwdxx &apos;);&lt;br/&gt;
109 del&lt;br/&gt;
&amp;lt; 0 rows inserted/updated/deleted&lt;br/&gt;
110 del&lt;br/&gt;
&amp;lt; ij&amp;gt; values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY(&apos;bootPassword&apos;);&lt;br/&gt;
110a107,110&lt;br/&gt;
&amp;gt; ERROR XBCXA: Wrong boot password.&lt;br/&gt;
&amp;gt; ij(CONNECTION1)&amp;gt; call SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY(&apos;bootPassword&apos;, &apos;bbderbypwdx, derbypwdxx &apos;);&lt;br/&gt;
&amp;gt; ERROR XBCXA: Wrong boot password.&lt;br/&gt;
&amp;gt; ij(CONNECTION1)&amp;gt; values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY(&apos;bootPassword&apos;);&lt;br/&gt;
114 del&lt;br/&gt;
&amp;lt; ij&amp;gt; values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY(&apos;encryptedBootPassword&apos;);&lt;br/&gt;
114a114&lt;br/&gt;
&amp;gt; ij(CONNECTION1)&amp;gt; values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY(&apos;encryptedBootPassword&apos;);&lt;br/&gt;
118 del&lt;br/&gt;
&amp;lt; ij&amp;gt; disconnect;&lt;br/&gt;
118a118&lt;br/&gt;
&amp;gt; ij(CONNECTION1)&amp;gt; disconnect;&lt;br/&gt;
124a125,126&lt;br/&gt;
&amp;gt; ERROR XJ040: Failed to start database &apos;wombat&apos; with class loader XXXX,  see the next exception for details.&lt;br/&gt;
&amp;gt; ERROR XBM06: Startup failed. An encrypted database cannot be accessed without the correct boot password.  &lt;br/&gt;
126 del&lt;br/&gt;
&amp;lt; A                   &lt;br/&gt;
127 del&lt;br/&gt;
&amp;lt; --------------------&lt;br/&gt;
128 del&lt;br/&gt;
&amp;lt; hello world         &lt;br/&gt;
128a128&lt;br/&gt;
&amp;gt; IJ ERROR: Unable to establish connection&lt;br/&gt;
132 del&lt;br/&gt;
&amp;lt; ERROR XBCXD: The encryption algorithm cannot be changed after the database is created.&lt;br/&gt;
132a132&lt;br/&gt;
&amp;gt; IJ ERROR: Unable to establish connection&lt;br/&gt;
134 del&lt;br/&gt;
&amp;lt; ERROR XBCXE: The encryption provider cannot be changed after the database is created.&lt;br/&gt;
134a134&lt;br/&gt;
&amp;gt; IJ ERROR: Unable to establish connection&lt;br/&gt;
Test Failed.&lt;/li&gt;
			&lt;li&gt;End:   encryptDatabase jdk1.6.0 encryptionAll:encryptionAES 2012-01-14 01:51:49 ***&lt;br/&gt;
------------------------------------------------------&lt;/li&gt;
		&lt;/ul&gt;
		&lt;/li&gt;
	&lt;/ul&gt;
	&lt;/li&gt;
&lt;/ul&gt;
</description>
                <environment>------------------ Java Information ------------------&lt;br/&gt;
Java Version:    1.6.0&lt;br/&gt;
Java Vendor:     IBM Corporation&lt;br/&gt;
Java home:       F:\jartest\ibm16\jre&lt;br/&gt;
Java classpath:  F:\jartest/tools/java/jakarta-oro-2.0.8.jar;F:\jartest/junit/junit.jar;;F:\jartest/classes/derbyrun.jar;F:\jartest/classes/derbyTesting.jar;F:\jartest/junit/junit.jar;F:\jartest/tools/java/jakarta-oro-2.0.8.jar;F:\jartest/tools/java/geronimo-spec-servlet-2.4-rc4.jar;F:\jartest/tools/java/xalan.jar;F:\jartest/tools/java/xercesImpl.jar;&lt;br/&gt;
OS name:         Windows XP&lt;br/&gt;
OS architecture: x86&lt;br/&gt;
OS version:      5.1 build 2600 Service Pack 3&lt;br/&gt;
Java user name:  cloudtest&lt;br/&gt;
Java user home:  C:\Documents and Settings\cloudtest&lt;br/&gt;
Java user dir:   F:\jartest\JarResults.2012-01-13\ibm16_derbyall&lt;br/&gt;
java.specification.name: Java Platform API Specification&lt;br/&gt;
java.specification.version: 1.6&lt;br/&gt;
java.runtime.version: jvmwi3260sr9-20110203_74623&lt;br/&gt;
java.fullversion: JRE 1.6.0 IBM J9 2.4 Windows XP x86-32 jvmwi3260sr9-20110203_74623 (JIT enabled, AOT enabled)&lt;br/&gt;
J9VM - 20110203_074623&lt;br/&gt;
JIT  - r9_20101028_17488ifx3&lt;br/&gt;
GC   - 20101027_AA&lt;br/&gt;
--------- Derby Information --------&lt;br/&gt;
JRE - JDBC: Java SE 6 - JDBC 4.0&lt;br/&gt;
[F:\jartest\classes\derby.jar] 10.7.1.4 - (1231439)&lt;br/&gt;
[F:\jartest\classes\derbytools.jar] 10.7.1.4 - (1231439)&lt;br/&gt;
[F:\jartest\classes\derbynet.jar] 10.7.1.4 - (1231439)&lt;br/&gt;
[F:\jartest\classes\derbyclient.jar] 10.7.1.4 - (1231439)&lt;br/&gt;
------------------------------------------------------&lt;br/&gt;
----------------- Locale Information -----------------&lt;br/&gt;
Current Locale :  [English/United States [en_US]]&lt;br/&gt;
Found support for locale: [cs]&lt;br/&gt;
	 version: 10.7.1.4 - (1231439)&lt;br/&gt;
Found support for locale: [de_DE]&lt;br/&gt;
	 version: 10.7.1.4 - (1231439)&lt;br/&gt;
Found support for locale: [es]&lt;br/&gt;
	 version: 10.7.1.4 - (1231439)&lt;br/&gt;
Found support for locale: [fr]&lt;br/&gt;
	 version: 10.7.1.4 - (1231439)&lt;br/&gt;
Found support for locale: [hu]&lt;br/&gt;
	 version: 10.7.1.4 - (1231439)&lt;br/&gt;
Found support for locale: [it]&lt;br/&gt;
	 version: 10.7.1.4 - (1231439)&lt;br/&gt;
Found support for locale: [ja_JP]&lt;br/&gt;
	 version: 10.7.1.4 - (1231439)&lt;br/&gt;
Found support for locale: [ko_KR]&lt;br/&gt;
	 version: 10.7.1.4 - (1231439)&lt;br/&gt;
Found support for locale: [pl]&lt;br/&gt;
	 version: 10.7.1.4 - (1231439)&lt;br/&gt;
Found support for locale: [pt_BR]&lt;br/&gt;
	 version: 10.7.1.4 - (1231439)&lt;br/&gt;
Found support for locale: [ru]&lt;br/&gt;
	 version: 10.7.1.4 - (1231439)&lt;br/&gt;
Found support for locale: [zh_CN]&lt;br/&gt;
	 version: 10.7.1.4 - (1231439)&lt;br/&gt;
Found support for locale: [zh_TW]&lt;br/&gt;
	 version: 10.7.1.4 - (1231439)&lt;br/&gt;
------------------------------------------------------&lt;br/&gt;
</environment>
        <key id="12538901">DERBY-5574</key>
            <summary>encryption test in encryption nightly suite test fails with ERROR XBM0S: Unable to rename file error</summary>
                <type id="1" iconUrl="https://issues.apache.org/jira/images/icons/issuetypes/bug.png">Bug</type>
                                            <priority id="3" iconUrl="https://issues.apache.org/jira/images/icons/priorities/major.png">Major</priority>
                        <status id="6" iconUrl="https://issues.apache.org/jira/images/icons/statuses/closed.png" description="The issue is considered finished, the resolution is correct. Issues which are closed can be reopened.">Closed</status>
                    <statusCategory id="3" key="done" colorName="green"/>
                                    <resolution id="1">Fixed</resolution>
                                        <assignee username="mikem">Mike Matrigali</assignee>
                                    <reporter username="mikem">Mike Matrigali</reporter>
                        <labels>
                    </labels>
                <created>Thu, 19 Jan 2012 00:00:31 +0000</created>
                <updated>Wed, 19 Jun 2013 18:19:26 +0100</updated>
                            <resolved>Tue, 14 Feb 2012 22:43:26 +0000</resolved>
                                    <version>10.7.1.4</version>
                                    <fixVersion>10.7.1.4</fixVersion>
                    <fixVersion>10.8.3.0</fixVersion>
                    <fixVersion>10.9.1.0</fixVersion>
                                    <component>Test</component>
                        <due></due>
                            <votes>0</votes>
                                    <watches>0</watches>
                                                                <comments>
                            <comment id="13188820" author="mikem" created="Thu, 19 Jan 2012 00:02:16 +0000"  >&lt;p&gt;failed also in same way against ibm16 in a run a week later against 10.7 head of brach&lt;/p&gt;

&lt;p&gt;&lt;a href=&quot;http://people.apache.org/~myrnavl/derby_test_results/v10_7/windows/testlog/ibm16/1231617-derbyall_diff.txt&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://people.apache.org/~myrnavl/derby_test_results/v10_7/windows/testlog/ibm16/1231617-derbyall_diff.txt&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Failure Details:&lt;/p&gt;
&lt;ul&gt;
	&lt;li&gt;
	&lt;ul&gt;
		&lt;li&gt;
		&lt;ul&gt;
			&lt;li&gt;
			&lt;ul&gt;
				&lt;li&gt;
				&lt;ul&gt;
					&lt;li&gt;
					&lt;ul&gt;
						&lt;li&gt;
						&lt;ul&gt;
							&lt;li&gt;
							&lt;ul&gt;
								&lt;li&gt;
								&lt;ul&gt;
									&lt;li&gt;Diff file derbyall/derbynetclientmats/DerbyNetClient/encodingTests/TestEnc.diff&lt;/li&gt;
								&lt;/ul&gt;
								&lt;/li&gt;
							&lt;/ul&gt;
							&lt;/li&gt;
						&lt;/ul&gt;
						&lt;/li&gt;
					&lt;/ul&gt;
					&lt;/li&gt;
				&lt;/ul&gt;
				&lt;/li&gt;
			&lt;/ul&gt;
			&lt;/li&gt;
			&lt;li&gt;Start: TestEnc jdk1.6.0 DerbyNetClient derbynetclientmats:encodingTests 2012-01-15 00:58:34 ***&lt;br/&gt;
derbyTesting.encoding can only be used with jdk15, skipping test&lt;/li&gt;
			&lt;li&gt;End:   TestEnc jdk1.6.0 DerbyNetClient derbynetclientmats:encodingTests 2012-01-15 00:58:34 ***
			&lt;ul&gt;
				&lt;li&gt;
				&lt;ul&gt;
					&lt;li&gt;
					&lt;ul&gt;
						&lt;li&gt;
						&lt;ul&gt;
							&lt;li&gt;
							&lt;ul&gt;
								&lt;li&gt;
								&lt;ul&gt;
									&lt;li&gt;Diff file derbyall/encryptionAll/encryptionECB/encryptDatabase.diff&lt;/li&gt;
								&lt;/ul&gt;
								&lt;/li&gt;
							&lt;/ul&gt;
							&lt;/li&gt;
						&lt;/ul&gt;
						&lt;/li&gt;
					&lt;/ul&gt;
					&lt;/li&gt;
				&lt;/ul&gt;
				&lt;/li&gt;
			&lt;/ul&gt;
			&lt;/li&gt;
			&lt;li&gt;Start: encryptDatabase jdk1.6.0 encryptionAll:encryptionECB 2012-01-15 01:04:22 ***&lt;br/&gt;
68 del&lt;br/&gt;
&amp;lt; 0 rows inserted/updated/deleted&lt;br/&gt;
68a68,70&lt;br/&gt;
&amp;gt; ERROR 38000: The exception &apos;org.apache.derby.iapi.error.PassThroughException: ERROR XBM0S: Unable to rename file &apos;F:\jartest\JarResults.2012-01-14\ibm16_derbyall\derbyall\encryptionAll\encryptionECB\encryptDatabase\wombat\service.properties&apos; to &apos;F:\jartest\JarResults.2012-01-14\ibm16_derbyall\derbyall\encryptionAll\encryptionECB\encryptDatabase\wombat\service.propertiesold&apos;&apos; was thrown while evaluating an expression.&lt;br/&gt;
&amp;gt; ERROR XJ001: Java exception: &apos;ERROR XBM0S: Unable to rename file &apos;F:\jartest\JarResults.2012-01-14\ibm16_derbyall\derbyall\encryptionAll\encryptionECB\encryptDatabase\wombat\service.properties&apos; to &apos;F:\jartest\JarResults.2012-01-14\ibm16_derbyall\derbyall\encryptionAll\encryptionECB\encryptDatabase\wombat\service.propertiesold&apos;: org.apache.derby.iapi.error.PassThroughException&apos;.&lt;br/&gt;
&amp;gt; ERROR XBM0S: Unable to rename file &apos;F:\jartest\JarResults.2012-01-14\ibm16_derbyall\derbyall\encryptionAll\encryptionECB\encryptDatabase\wombat\service.properties&apos; to &apos;F:\jartest\JarResults.2012-01-14\ibm16_derbyall\derbyall\encryptionAll\encryptionECB\encryptDatabase\wombat\service.propertiesold&apos;&lt;br/&gt;
74 del&lt;br/&gt;
&amp;lt; 0 rows inserted/updated/deleted&lt;br/&gt;
74a76,78&lt;br/&gt;
&amp;gt; ERROR 38000: The exception &apos;org.apache.derby.iapi.error.PassThroughException: ERROR XBM0S: Unable to rename file &apos;F:\jartest\JarResults.2012-01-14\ibm16_derbyall\derbyall\encryptionAll\encryptionECB\encryptDatabase\wombat\service.properties&apos; to &apos;F:\jartest\JarResults.2012-01-14\ibm16_derbyall\derbyall\encryptionAll\encryptionECB\encryptDatabase\wombat\service.propertiesold&apos;&apos; was thrown while evaluating an expression.&lt;br/&gt;
&amp;gt; ERROR XJ001: Java exception: &apos;ERROR XBM0S: Unable to rename file &apos;F:\jartest\JarResults.2012-01-14\ibm16_derbyall\derbyall\encryptionAll\encryptionECB\encryptDatabase\wombat\service.properties&apos; to &apos;F:\jartest\JarResults.2012-01-14\ibm16_derbyall\derbyall\encryptionAll\encryptionECB\encryptDatabase\wombat\service.propertiesold&apos;: org.apache.derby.iapi.error.PassThroughException&apos;.&lt;br/&gt;
&amp;gt; ERROR XBM0S: Unable to rename file &apos;F:\jartest\JarResults.2012-01-14\ibm16_derbyall\derbyall\encryptionAll\encryptionECB\encryptDatabase\wombat\service.properties&apos; to &apos;F:\jartest\JarResults.2012-01-14\ibm16_derbyall\derbyall\encryptionAll\encryptionECB\encryptDatabase\wombat\service.propertiesold&apos;&lt;br/&gt;
91,92d94&lt;br/&gt;
&amp;lt; ERROR XJ040: Failed to start database &apos;wombat&apos; with class loader XXXX,  see the next exception for details.&lt;br/&gt;
&amp;lt; ERROR XBM06: Startup failed. An encrypted database cannot be accessed without the correct boot password.  &lt;br/&gt;
94 del&lt;br/&gt;
&amp;lt; ERROR XJ040: Failed to start database &apos;wombat&apos; with class loader XXXX,  see the next exception for details.&lt;br/&gt;
95 del&lt;br/&gt;
&amp;lt; ERROR XBM06: Startup failed. An encrypted database cannot be accessed without the correct boot password.  &lt;br/&gt;
96 del&lt;br/&gt;
&amp;lt; ij&amp;gt; connect &apos;jdbc:derby:wombat;bootPassword=derbypwd&apos;;&lt;br/&gt;
97 del&lt;br/&gt;
&amp;lt; ij&amp;gt; values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY(&apos;bootPassword&apos;);&lt;br/&gt;
97a96,97&lt;br/&gt;
&amp;gt; ij(CONNECTION1)&amp;gt; connect &apos;jdbc:derby:wombat;bootPassword=derbypwd&apos;;&lt;br/&gt;
&amp;gt; ij(CONNECTION2)&amp;gt; values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY(&apos;bootPassword&apos;);&lt;br/&gt;
101 del&lt;br/&gt;
&amp;lt; ij&amp;gt; values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY(&apos;encryptedBootPassword&apos;);&lt;br/&gt;
101a101&lt;br/&gt;
&amp;gt; ij(CONNECTION2)&amp;gt; values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY(&apos;encryptedBootPassword&apos;);&lt;br/&gt;
105 del&lt;br/&gt;
&amp;lt; ij&amp;gt; &amp;#8211; change it again, make sure it trims white spaces&lt;br/&gt;
105a105&lt;br/&gt;
&amp;gt; ij(CONNECTION2)&amp;gt; &amp;#8211; change it again, make sure it trims white spaces&lt;br/&gt;
107 del&lt;br/&gt;
&amp;lt; 0 rows inserted/updated/deleted&lt;br/&gt;
108 del&lt;br/&gt;
&amp;lt; ij&amp;gt; call SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY(&apos;bootPassword&apos;, &apos;bbderbypwdx, derbypwdxx &apos;);&lt;br/&gt;
109 del&lt;br/&gt;
&amp;lt; 0 rows inserted/updated/deleted&lt;br/&gt;
110 del&lt;br/&gt;
&amp;lt; ij&amp;gt; values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY(&apos;bootPassword&apos;);&lt;br/&gt;
110a107,110&lt;br/&gt;
&amp;gt; ERROR XBCXA: Wrong boot password.&lt;br/&gt;
&amp;gt; ij(CONNECTION2)&amp;gt; call SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY(&apos;bootPassword&apos;, &apos;bbderbypwdx, derbypwdxx &apos;);&lt;br/&gt;
&amp;gt; ERROR XBCXA: Wrong boot password.&lt;br/&gt;
&amp;gt; ij(CONNECTION2)&amp;gt; values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY(&apos;bootPassword&apos;);&lt;br/&gt;
114 del&lt;br/&gt;
&amp;lt; ij&amp;gt; values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY(&apos;encryptedBootPassword&apos;);&lt;br/&gt;
114a114&lt;br/&gt;
&amp;gt; ij(CONNECTION2)&amp;gt; values SYSCS_UTIL.SYSCS_GET_DATABASE_PROPERTY(&apos;encryptedBootPassword&apos;);&lt;br/&gt;
118 del&lt;br/&gt;
&amp;lt; ij&amp;gt; disconnect;&lt;br/&gt;
118a118&lt;br/&gt;
&amp;gt; ij(CONNECTION2)&amp;gt; disconnect;&lt;br/&gt;
124a125,126&lt;br/&gt;
&amp;gt; ERROR XJ040: Failed to start database &apos;wombat&apos; with class loader XXXX,  see the next exception for details.&lt;br/&gt;
&amp;gt; ERROR XBM06: Startup failed. An encrypted database cannot be accessed without the correct boot password.  &lt;br/&gt;
126 del&lt;br/&gt;
&amp;lt; A                   &lt;br/&gt;
127 del&lt;br/&gt;
&amp;lt; --------------------&lt;br/&gt;
128 del&lt;br/&gt;
&amp;lt; hello world         &lt;br/&gt;
128a128&lt;br/&gt;
&amp;gt; IJ ERROR: Unable to establish connection&lt;br/&gt;
132 del&lt;br/&gt;
&amp;lt; ERROR XBCXD: The encryption algorithm cannot be changed after the database is created.&lt;br/&gt;
132a132&lt;br/&gt;
&amp;gt; IJ ERROR: Unable to establish connection&lt;br/&gt;
134 del&lt;br/&gt;
&amp;lt; ERROR XBCXE: The encryption provider cannot be changed after the database is created.&lt;br/&gt;
134a134&lt;br/&gt;
&amp;gt; IJ ERROR: Unable to establish connection&lt;br/&gt;
Test Failed.&lt;/li&gt;
			&lt;li&gt;End:   encryptDatabase jdk1.6.0 encryptionAll:encryptionECB 2012-01-15 01:04:32 ***&lt;/li&gt;
		&lt;/ul&gt;
		&lt;/li&gt;
	&lt;/ul&gt;
	&lt;/li&gt;
&lt;/ul&gt;
</comment>
                            <comment id="13189207" author="mikem" created="Thu, 19 Jan 2012 17:13:35 +0000"  >&lt;p&gt;changing title as different tests in the encryption suite seem to be failing intermittently.&lt;/p&gt;</comment>
                            <comment id="13189228" author="mikem" created="Thu, 19 Jan 2012 17:43:30 +0000"  >&lt;p&gt;here is derby.log left around after one of the errors.&lt;/p&gt;</comment>
                            <comment id="13189230" author="mikem" created="Thu, 19 Jan 2012 17:46:32 +0000"  >&lt;p&gt;here are the stacks from first error in one of the failures:&lt;br/&gt;
Thu Jan 19 00:35:33 PST 2012 Thread&lt;span class=&quot;error&quot;&gt;&amp;#91;main,5,main&amp;#93;&lt;/span&gt; (XID = 211), (SESSIONID = 1), (DATABASE = wombat), (DRDAID = null), Failed Statement is: &amp;#8211; change it again&lt;br/&gt;
call SYSCS_UTIL.SYSCS_SET_DATABASE_PROPERTY(&apos;bootPassword&apos;, &apos;Saturday,derbypwd&apos;)&lt;br/&gt;
ERROR 38000: The exception &apos;org.apache.derby.iapi.error.PassThroughException: ERROR XBM0S: Unable to rename file &apos;D:\jartest\JarResults.2012-01-18\ibm16_derbyall\derbyall\encryptionAll\encryption\encryption\encryptDatabase\wombat\service.properties&apos; to &apos;D:\jartest\JarResults.2012-01-18\ibm16_derbyall\derbyall\encryptionAll\encryption\encryption\encryptDatabase\wombat\service.propertiesold&apos;&apos; was thrown while evaluating an expression.&lt;br/&gt;
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.iapi.error.StandardException.unexpectedUserException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.services.reflect.ReflectMethod.invoke(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.sql.execute.CallStatementResultSet.open(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.ij.executeImmediate(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.utilMain.doCatch(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.utilMain.runScriptGuts(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.utilMain.go(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.Main.go(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.Main.mainCore(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.Main.main(Unknown Source)&lt;br/&gt;
	at org.apache.derby.tools.ij.main(Unknown Source)&lt;br/&gt;
Caused by: org.apache.derby.iapi.error.PassThroughException: ERROR XBM0S: Unable to rename file &apos;D:\jartest\JarResults.2012-01-18\ibm16_derbyall\derbyall\encryptionAll\encryption\encryption\encryptDatabase\wombat\service.properties&apos; to &apos;D:\jartest\JarResults.2012-01-18\ibm16_derbyall\derbyall\encryptionAll\encryption\encryption\encryptDatabase\wombat\service.propertiesold&apos;&lt;br/&gt;
	at org.apache.derby.impl.services.monitor.UpdateServiceProperties.update(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.services.monitor.UpdateServiceProperties.put(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.services.jce.JCECipherFactory.changeBootPassword(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.store.raw.RawStore.changeBootPassword(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.store.access.PropertyConglomerate.bootPasswordChange(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.store.access.PropertyConglomerate.setProperty(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.store.access.RAMTransaction.setProperty(Unknown Source)&lt;br/&gt;
	at org.apache.derby.iapi.db.PropertyInfo.setDatabaseProperty(Unknown Source)&lt;br/&gt;
	at org.apache.derby.catalog.SystemProcedures.SYSCS_SET_DATABASE_PROPERTY(Unknown Source)&lt;br/&gt;
	at org.apache.derby.exe.ac80220011x0134xf51bx34daxffffbee07f83f.g0(Unknown Source)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)&lt;br/&gt;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)&lt;br/&gt;
	at java.lang.reflect.Method.invoke(Method.java:611)&lt;br/&gt;
	... 15 more&lt;br/&gt;
Caused by: ERROR XBM0S: Unable to rename file &apos;D:\jartest\JarResults.2012-01-18\ibm16_derbyall\derbyall\encryptionAll\encryption\encryption\encryptDatabase\wombat\service.properties&apos; to &apos;D:\jartest\JarResults.2012-01-18\ibm16_derbyall\derbyall\encryptionAll\encryption\encryption\encryptDatabase\wombat\service.propertiesold&apos;&lt;br/&gt;
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.renameTo(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.services.monitor.StorageFactoryService$5.run(Unknown Source)&lt;br/&gt;
	at java.security.AccessController.doPrivileged(AccessController.java:251)&lt;br/&gt;
	at org.apache.derby.impl.services.monitor.StorageFactoryService.saveServiceProperties(Unknown Source)&lt;br/&gt;
	... 29 more&lt;br/&gt;
============= begin nested exception, level (1) ===========&lt;br/&gt;
org.apache.derby.iapi.error.PassThroughException: ERROR XBM0S: Unable to rename file &apos;D:\jartest\JarResults.2012-01-18\ibm16_derbyall\derbyall\encryptionAll\encryption\encryption\encryptDatabase\wombat\service.properties&apos; to &apos;D:\jartest\JarResults.2012-01-18\ibm16_derbyall\derbyall\encryptionAll\encryption\encryption\encryptDatabase\wombat\service.propertiesold&apos;&lt;br/&gt;
	at org.apache.derby.impl.services.monitor.UpdateServiceProperties.update(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.services.monitor.UpdateServiceProperties.put(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.services.jce.JCECipherFactory.changeBootPassword(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.store.raw.RawStore.changeBootPassword(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.store.access.PropertyConglomerate.bootPasswordChange(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.store.access.PropertyConglomerate.setProperty(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.store.access.RAMTransaction.setProperty(Unknown Source)&lt;br/&gt;
	at org.apache.derby.iapi.db.PropertyInfo.setDatabaseProperty(Unknown Source)&lt;br/&gt;
	at org.apache.derby.catalog.SystemProcedures.SYSCS_SET_DATABASE_PROPERTY(Unknown Source)&lt;br/&gt;
	at org.apache.derby.exe.ac80220011x0134xf51bx34daxffffbee07f83f.g0(Unknown Source)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)&lt;br/&gt;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)&lt;br/&gt;
	at java.lang.reflect.Method.invoke(Method.java:611)&lt;br/&gt;
	at org.apache.derby.impl.services.reflect.ReflectMethod.invoke(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.sql.execute.CallStatementResultSet.open(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.ij.executeImmediate(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.utilMain.doCatch(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.utilMain.runScriptGuts(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.utilMain.go(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.Main.go(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.Main.mainCore(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.Main.main(Unknown Source)&lt;br/&gt;
	at org.apache.derby.tools.ij.main(Unknown Source)&lt;br/&gt;
Caused by: ERROR XBM0S: Unable to rename file &apos;D:\jartest\JarResults.2012-01-18\ibm16_derbyall\derbyall\encryptionAll\encryption\encryption\encryptDatabase\wombat\service.properties&apos; to &apos;D:\jartest\JarResults.2012-01-18\ibm16_derbyall\derbyall\encryptionAll\encryption\encryption\encryptDatabase\wombat\service.propertiesold&apos;&lt;br/&gt;
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.renameTo(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.services.monitor.StorageFactoryService$5.run(Unknown Source)&lt;br/&gt;
	at java.security.AccessController.doPrivileged(AccessController.java:251)&lt;br/&gt;
	at org.apache.derby.impl.services.monitor.StorageFactoryService.saveServiceProperties(Unknown Source)&lt;br/&gt;
	... 29 more&lt;br/&gt;
============= end nested exception, level (1) ===========&lt;br/&gt;
============= begin nested exception, level (2) ===========&lt;br/&gt;
ERROR XBM0S: Unable to rename file &apos;D:\jartest\JarResults.2012-01-18\ibm16_derbyall\derbyall\encryptionAll\encryption\encryption\encryptDatabase\wombat\service.properties&apos; to &apos;D:\jartest\JarResults.2012-01-18\ibm16_derbyall\derbyall\encryptionAll\encryption\encryption\encryptDatabase\wombat\service.propertiesold&apos;&lt;br/&gt;
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.services.monitor.StorageFactoryService$FileOperationHelper.renameTo(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.services.monitor.StorageFactoryService$5.run(Unknown Source)&lt;br/&gt;
	at java.security.AccessController.doPrivileged(AccessController.java:251)&lt;br/&gt;
	at org.apache.derby.impl.services.monitor.StorageFactoryService.saveServiceProperties(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.services.monitor.UpdateServiceProperties.update(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.services.monitor.UpdateServiceProperties.put(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.services.jce.JCECipherFactory.changeBootPassword(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.store.raw.RawStore.changeBootPassword(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.store.access.PropertyConglomerate.bootPasswordChange(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.store.access.PropertyConglomerate.setProperty(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.store.access.RAMTransaction.setProperty(Unknown Source)&lt;br/&gt;
	at org.apache.derby.iapi.db.PropertyInfo.setDatabaseProperty(Unknown Source)&lt;br/&gt;
	at org.apache.derby.catalog.SystemProcedures.SYSCS_SET_DATABASE_PROPERTY(Unknown Source)&lt;br/&gt;
	at org.apache.derby.exe.ac80220011x0134xf51bx34daxffffbee07f83f.g0(Unknown Source)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br/&gt;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)&lt;br/&gt;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)&lt;br/&gt;
	at java.lang.reflect.Method.invoke(Method.java:611)&lt;br/&gt;
	at org.apache.derby.impl.services.reflect.ReflectMethod.invoke(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.sql.execute.CallStatementResultSet.open(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.jdbc.EmbedStatement.execute(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.ij.executeImmediate(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.utilMain.doCatch(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.utilMain.runScriptGuts(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.utilMain.go(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.Main.go(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.Main.mainCore(Unknown Source)&lt;br/&gt;
	at org.apache.derby.impl.tools.ij.Main.main(Unknown Source)&lt;br/&gt;
	at org.apache.derby.tools.ij.main(Unknown Source)&lt;br/&gt;
============= end nested exception, level (2) ===========&lt;br/&gt;
Cleanup action completed&lt;br/&gt;
----------------------------------------------------------------&lt;br/&gt;
Thu Jan 19 00:35:33 PST 2012: Shutting down Derby engine&lt;/p&gt;</comment>
                            <comment id="13189262" author="mikem" created="Thu, 19 Jan 2012 18:25:34 +0000"  >&lt;p&gt;unfortunately it looks like the code will eventually call File.renameTo() which looks like it will swallow any OS generated errors, and hide&lt;br/&gt;
them, returning just false if it didn&apos;t work. &lt;/p&gt;

&lt;p&gt;My take on the test is that a lot of renaming of service.properties to service.propertiesold is happening in this test.   And since the test passes&lt;br/&gt;
almost everywhere it is unlikely we are not closing the file correctly.  So some sort of timing or resource issue is happening in this environment.&lt;br/&gt;
Some of the other new errors that seem to be cropping up new in this environment also have the feel of a temporary resource issue of some sort.&lt;/p&gt;

&lt;p&gt;Does anyone see a problem with adding some retry logic to the rename, similar to what we do for other failed I/O operations?&lt;/p&gt;</comment>
                            <comment id="13191420" author="mikem" created="Mon, 23 Jan 2012 20:25:04 +0000"  >&lt;p&gt;proposed patch to retry on rename failures.  passed full test suite run on my machine.&lt;/p&gt;</comment>
                            <comment id="13194259" author="mikem" created="Thu, 26 Jan 2012 23:14:16 +0000"  >&lt;p&gt;backported retry on rename to 10.8 and 10.7.  Going to let changes sit for awhile to see if problem still shows up.  I have only seen error intermittently in nightly runs, have not been able to reproduce in my environment.  Definitely log new instances of problem in this JIRA.  Change can be backported further but will need to be mondified slightly to not&lt;br/&gt;
use the InterruptStatus class.&lt;/p&gt;</comment>
                            <comment id="13208091" author="mikem" created="Tue, 14 Feb 2012 22:43:26 +0000"  >&lt;p&gt;have not seen error since retry was added.  closing issue for now, reopen if seen again in 10.7, 10.8 or trunk  branches after date of the comment.  Change was &lt;br/&gt;
submitted to trunk, 10.7 and 10.8 prior to this comment.&lt;/p&gt;</comment>
                    </comments>
                <issuelinks>
                            <issuelinktype id="12310000">
                    <name>Duplicate</name>
                                                                <inwardlinks description="is duplicated by">
                                        <issuelink>
            <issuekey id="12504109">DERBY-5188</issuekey>
        </issuelink>
                            </inwardlinks>
                                    </issuelinktype>
                    </issuelinks>
                <attachments>
                            <attachment id="12511144" name="derby.log" size="134666" author="mikem" created="Thu, 19 Jan 2012 17:43:30 +0000"/>
                            <attachment id="12511549" name="derby5574.diff" size="2578" author="mikem" created="Mon, 23 Jan 2012 20:25:04 +0000"/>
                    </attachments>
                <subtasks>
                    </subtasks>
                <customfields>
                                                <customfield id="customfield_12310310" key="com.atlassian.jira.toolkit:attachments">
                        <customfieldname>Attachment count</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>2.0</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                                                                                                        <customfield id="customfield_12310200" key="com.atlassian.jira.plugin.system.customfieldtypes:multicheckboxes">
                        <customfieldname>Bug behavior facts</customfieldname>
                        <customfieldvalues>
                                <customfieldvalue key="10369"><![CDATA[Regression Test Failure]]></customfieldvalue>
    
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <customfield id="customfield_12310420" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Global Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>224404</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                <customfield id="customfield_12311820" key="com.pyxis.greenhopper.jira:gh-lexo-rank">
                        <customfieldname>Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>2|hy0ctb:</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                <customfield id="customfield_12310920" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Rank (Obsolete)</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>35894</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                        <customfield id="customfield_12310222" key="com.atlassian.jira.ext.charting:timeinstatus">
                        <customfieldname>Time in Status</customfieldname>
                        <customfieldvalues>
                            
                        </customfieldvalues>
                    </customfield>
                                                                                            </customfields>
    </item>
</channel>
</rss>