can't call a stored function with an aggregate argument without getting the following error: ERROR 42Y29