DRDAConnThread.closeStream():

	} catch (IOException e) 
{
	    Util.javaException(e);
	    
	}

DRDAStatement.execute():

		} catch (IOException e) 
{ 
			Util.javaException(e);
		}

Since Util.javaException() only returns an exception, this code doesn't work as intended. The returned exception should also be thrown.