I'm seeing this on trunk:


ij version 10.11
ij> connect 'jdbc:derby:memory:db;create=true';
ij> create table t1(x int, y int, z int);
0 rows inserted/updated/deleted
ij> create table t2(x int, y int, z int);
0 rows inserted/updated/deleted
ij> create sequence seq;
0 rows inserted/updated/deleted
ij> values next value for seq;
1          
-----------
-2147483648

1 row selected
ij> create trigger tr1 after insert on t1 insert into t2(x) values (next value for seq);
ERROR 40XT8: An internal error was identified by RawStore module. Internal state detail from the transaction is as follows: savedEndStatus = 0
needSync = false
justCreated = false
myGlobalId = null
myId = null
state = 0
inComplete = null
seenUpdates = false
inPostCommitProcessing = false
logStart = null
logLast = null
recoveryTransaction = false
postCompleteMode = false
sanityCheck_xaclosed = false
transName = UserTransaction
readOnly = false
flush_log_on_xact_end = true
backupBlocked = false
dontWaitForLocks = false

